# version = "Two"
# unstable_features = false

max_width = 120
edition = "2021"
newline_style = "Unix"
# format_strings = false

# Comments
# comment_width = 100
# normalize_comments = true
# wrap_comments = true
# format_code_in_doc_comments = true
# normalize_doc_attributes = true

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Macros
# format_macro_matchers = true
# format_macro_bodies = true

# reorder_impl_items = true

use_try_shorthand = true
use_field_init_shorthand = true

# report_todo = "Always"
# report_fixme = "Always"
